FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.ingestion.txt .
RUN pip install --no-cache-dir -r requirements.ingestion.txt

COPY ingestion/ ./ingestion/
COPY api/ ./api/
COPY core/ ./core/
COPY config.py .
COPY .env .

EXPOSE 5027

CMD ["python", "ingestion/main.py"]
